project:
  type: website
  output-dir: docs

website:
  repo-url: https://github.com/jack-davison/jack-davison.github.io
  open-graph: true
  site-url: https://jack-davison.github.io/
  navbar:
    title: Jack Davison
    search: true
    right:
      - text: "Experience"
        file: experience.qmd
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "Blog"
        file: blog.qmd
      - icon: twitter
        href: https://twitter.com/jdavison_
      - icon: mastodon
        href: https://fosstodon.org/@jackdavison
      - icon: github
        href: https://github.com/jack-davison
      - icon: linkedin
        href: https://www.linkedin.com/in/jack-davison/
  page-footer:
    left: |
      <span>Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
    center: |
      <img src='/style/logo.png' style='width:7.5%'>
    right: |
      <span>[View the source at {{< fa brands github >}} GitHub](https://github.com/jack-davison/jack-davison.github.io)</span>

format:
  html:
    toc: true
    toc-location: "left"
    code-link: true
    code-overflow: wrap
    anchor-sections: true
    footnotes-hover: true
    fontsize: 1em
    theme: [minty, style/styles.scss]
    css: style/styles.css
    title-block-banner-color: white
    mainfont: Poppins
    monofont: JetBrains Mono

bibliography: references.bib

