project:
  type: website
  output-dir: docs

website:
  repo-url: https://github.com/jack-davison/jack-davison.github.io
  open-graph: true
  site-url: https://jack-davison.github.io/
  navbar:
    logo: logo.png
    search: true
    right:
      - text: "About"
        file: index.qmd
      - text: "Experience"
        file: experience.qmd
      - text: "Blog"
        file: blog.qmd
      - icon: twitter
        href: https://twitter.com/jdavison_
      - icon: github
        href: https://github.com/jack-davison
      - icon: linkedin
        href: https://www.linkedin.com/in/jack-davison/
format:
  html:
    toc: true
    toc-location: "left"
    code-link: true
    code-overflow: wrap
    anchor-sections: true
    footnotes-hover: true
    fontsize: 1em
    theme: simplex
    css: styles.css

bibliography: references.bib
