---
title: Portfolio
subtitle: A collection of publications, presentations, and projects.
listing:
  - id: lst-academic
    contents: portfolio/academic.yaml
    type: default
    sort-ui: true
    sort: [date desc]
    categories: true
    date-format: "DD-MM-YYYY"
  - id: lst-professional
    contents: portfolio/professional.yaml
    type: default
    sort-ui: true
    sort: [date desc]
    date-format: "DD-MM-YYYY"
  - id: lst-talks
    contents: portfolio/talks.yaml
    type: default
    sort-ui: true
    sort: [date desc]
    date-format: "DD-MM-YYYY"
  - id: lst-software
    contents: portfolio/software.yaml
    type: default
    sort-ui: true
    sort: [date desc]
    date-format: "DD-MM-YYYY"
  - id: lst-other
    contents: portfolio/other.yaml
    type: default
    sort-ui: false
    sort: [date desc]
    date-format: "DD-MM-YYYY"
page-layout: full
title-block-banner: true
---



:::: {.panel-tabset}

## Professional Publications

:::{.callout-note appearance="minimal"}
This is a selection of publications I've authored in my professional life. While this list isn't complete it shows a sample of the sorts of things I've been involved in. Some of these find their way to [{{< fa brands linkedin >}} LinkedIn](https://www.linkedin.com/in/jack-davison/).
:::

:::{#lst-professional}
:::

## Academic Publications

:::{.callout-note appearance="minimal"}
While I am no longer in academia, I have a catalogue of historical first-author publications and still contribute to research in atmospheric chemistry and emissions science. My ORCID iD is [{{< fa brands orcid >}} 0000-0003-2653-6615](https://orcid.org/0000-0003-2653-6615).
:::

:::{#lst-academic}
:::

## Software

:::{.callout-note appearance="minimal"}
I am an R developer with experience in package and Shiny app development. All of my public code can be found on my [GitHub {{< fa brands github >}} profile](https://github.com/jack-davison), but this section outlines a few examples.
:::

:::{#lst-software}
:::


## Presentations

:::{.callout-note appearance="minimal"}
I teach and present as much as I'm able. This is a collection of some of my public talks I've given, most commonly about data analysis techniques and environmental data science.
:::

:::{#lst-talks}
:::

## Other

:::{.callout-note appearance="minimal"}
This is a collection of odds and ends that I've made that don't quite fit into other categories - things like random personal projects and contest entries I've not written a blog post about.
:::

:::{#lst-other}
:::

::::
